# Generated by Django 5.0.3 on 2024-04-15 21:42

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_img_course_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
