# Generated by Django 5.0.3 on 2024-04-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '4. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Students'},
        ),
    ]
