# Generated by Django 5.0.3 on 2024-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_chapter_options_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='remarks',
            field=models.TextField(default='Chapter remarks/details'),
        ),
    ]
