# Generated by Django 5.0.6 on 2024-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
