# Generated by Django 5.0.6 on 2024-07-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_course_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
