# Generated by Django 5.0.6 on 2024-07-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_courserating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserating',
            old_name='enrolled_time',
            new_name='review_time',
        ),
    ]
