# Generated by Django 5.0.6 on 2024-08-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_enrolled_time_courserating_review_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Courses Rating and Review'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrolment',
            options={'ordering': ['enrolled_time'], 'verbose_name_plural': '6. Enrolled Courses'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teacher_profile_imgs'),
        ),
    ]
